image:
  - Visual Studio 2022

platform: x64

branches:
  only:
    - master
    - appveyor

skip_tags: true

install:
  - cmd: if not exist "C:\strawberry" cinst strawberryperl
  - cmd: set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - perl -v

build_script:
  - perl Makefile.PL
  - cmd: gmake test
